<?php

/**
 * Generated by the WordPress Option Page generator
 * at http://jeremyhixon.com/wp-tools/option-page/
 */

class InnovaInsightsHubPluginOptions {
	private $innova_insights_hub_plugin_options_options;

	public function __construct() {
		add_action( 'admin_menu', array( $this, 'innova_insights_hub_plugin_options_add_plugin_page' ) );
		add_action( 'admin_init', array( $this, 'innova_insights_hub_plugin_options_page_init' ) );
	}

	public function innova_insights_hub_plugin_options_add_plugin_page() {
		add_management_page(
			'Innova Insights Hub Plugin Options', // page_title
			'Innova Insights Hub Plugin Options', // menu_title
			'manage_options', // capability
			'innova-insights-hub-plugin-options', // menu_slug
			array( $this, 'innova_insights_hub_plugin_options_create_admin_page' ) // function
		);
	}

	public function innova_insights_hub_plugin_options_create_admin_page() {
		$this->innova_insights_hub_plugin_options_options = get_option( 'innova_insights_hub_plugin_options_option_name' ); ?>

		<div class="wrap">
			<h2>Innova Insights Hub Plugin Options</h2>
			<p>Set the options for the Innova Insights Hub Plugin</p>
			<?php settings_errors(); ?>

			<form method="post" action="options.php">
				<?php
				settings_fields( 'innova_insights_hub_plugin_options_option_group' );
				do_settings_sections( 'innova-insights-hub-plugin-options-admin' );
				submit_button();
				?>
			</form>
		</div>
	<?php }

	public function innova_insights_hub_plugin_options_page_init() {
		register_setting(
			'innova_insights_hub_plugin_options_option_group', // option_group
			'innova_insights_hub_plugin_options_option_name', // option_name
			array( $this, 'innova_insights_hub_plugin_options_sanitize' ) // sanitize_callback
		);

		add_settings_section(
			'innova_insights_hub_plugin_options_setting_section', // id
			'Settings', // title
			array( $this, 'innova_insights_hub_plugin_options_section_info' ), // callback
			'innova-insights-hub-plugin-options-admin' // page
		);

		add_settings_field(
			'api_key_0', // id
			'API Key', // title
			array( $this, 'api_key_0_callback' ), // callback
			'innova-insights-hub-plugin-options-admin', // page
			'innova_insights_hub_plugin_options_setting_section' // section
		);

		add_settings_field(
			'api_endpoint_url_1', // id
			'API endpoint URL', // title
			array( $this, 'api_endpoint_url_1_callback' ), // callback
			'innova-insights-hub-plugin-options-admin', // page
			'innova_insights_hub_plugin_options_setting_section' // section
		);
	}

	public function innova_insights_hub_plugin_options_sanitize($input) {
		$sanitary_values = array();
		if ( isset( $input['api_key_0'] ) ) {
			$sanitary_values['api_key_0'] = sanitize_text_field( $input['api_key_0'] );
		}

		if ( isset( $input['api_endpoint_url_1'] ) ) {
			$sanitary_values['api_endpoint_url_1'] = sanitize_text_field( $input['api_endpoint_url_1'] );
		}

		return $sanitary_values;
	}

	public function innova_insights_hub_plugin_options_section_info() {

	}

	public function api_key_0_callback() {
		printf(
			'<input class="regular-text" type="text" name="innova_insights_hub_plugin_options_option_name[api_key_0]" id="api_key_0" value="%s">',
			isset( $this->innova_insights_hub_plugin_options_options['api_key_0'] ) ? esc_attr( $this->innova_insights_hub_plugin_options_options['api_key_0']) : ''
		);
	}

	public function api_endpoint_url_1_callback() {
		printf(
			'<input class="regular-text" type="text" name="innova_insights_hub_plugin_options_option_name[api_endpoint_url_1]" id="api_endpoint_url_1" value="%s">',
			isset( $this->innova_insights_hub_plugin_options_options['api_endpoint_url_1'] ) ? esc_attr( $this->innova_insights_hub_plugin_options_options['api_endpoint_url_1']) : ''
		);
	}

}
if ( is_admin() )
	$innova_insights_hub_plugin_options = new InnovaInsightsHubPluginOptions();

/*
 * Retrieve this value with:
 * $innova_insights_hub_plugin_options_options = get_option( 'innova_insights_hub_plugin_options_option_name' ); // Array of All Options
 * $api_key_0 = $innova_insights_hub_plugin_options_options['api_key_0']; // API Key
 * $api_endpoint_url_1 = $innova_insights_hub_plugin_options_options['api_endpoint_url_1']; // API endpoint URL
 */
